import 'package:flutter/material.dart';
import 'package:flutter_gen/gen_l10n/app_localizations.dart';

class CategoryNames {
  static List<String> getCategories(BuildContext context) {
    return [
      AppLocalizations.of(context)!.categoryAction,
      AppLocalizations.of(context)!.categoryComedy,
      AppLocalizations.of(context)!.categoryDrama,
      AppLocalizations.of(context)!.categoryThriller,
      AppLocalizations.of(context)!.categoryHorror,
      AppLocalizations.of(context)!.categorySciFi,
      AppLocalizations.of(context)!.categoryFantasy,
      AppLocalizations.of(context)!.categoryAnimation,
      AppLocalizations.of(context)!.categoryAdventure,
      AppLocalizations.of(context)!.categoryWar,
      AppLocalizations.of(context)!.categoryRomCom,
      AppLocalizations.of(context)!.categoryCrime,
      AppLocalizations.of(context)!.categoryPsychoThriller,
      AppLocalizations.of(context)!.categoryHistorical,
      AppLocalizations.of(context)!.categoryDocumentary,
      AppLocalizations.of(context)!.categoryDystopian,
      AppLocalizations.of(context)!.categorySuperhero,
      AppLocalizations.of(context)!.categorySpy,
      AppLocalizations.of(context)!.categoryIndependent,
      AppLocalizations.of(context)!.categoryAnime,
      AppLocalizations.of(context)!.categoryMusical,
      AppLocalizations.of(context)!.categoryWestern,
      AppLocalizations.of(context)!.categoryNoir,
      AppLocalizations.of(context)!.categoryFamily,
      AppLocalizations.of(context)!.categorySupernatural,
    ];
  }

  static List<String> getBookCategories(BuildContext context) {
    return [
      AppLocalizations.of(context)!.categoryNovel,
      AppLocalizations.of(context)!.categoryStory,
      AppLocalizations.of(context)!.categoryPoetry,
      AppLocalizations.of(context)!.categoryTheatre,
      AppLocalizations.of(context)!.categorySciFiBook,
      AppLocalizations.of(context)!.categoryFantasyBook,
      AppLocalizations.of(context)!.categoryDystopianBook,
      AppLocalizations.of(context)!.categoryHorrorBook,
      AppLocalizations.of(context)!.categoryDetective,
      AppLocalizations.of(context)!.categoryBiography,
      AppLocalizations.of(context)!.categoryAutobiography,
      AppLocalizations.of(context)!.categoryHistory,
      AppLocalizations.of(context)!.categoryTravelWriting,
      AppLocalizations.of(context)!.categoryDiary,
      AppLocalizations.of(context)!.categoryPhilosophy,
      AppLocalizations.of(context)!.categoryPsychology,
      AppLocalizations.of(context)!.categorySociology,
      AppLocalizations.of(context)!.categorySciTech,
      AppLocalizations.of(context)!.categoryPoliticalScience,
      AppLocalizations.of(context)!.categoryRomance,
      AppLocalizations.of(context)!.categoryPsychologicalNovel,
      AppLocalizations.of(context)!.categoryFamilyNovel,
      AppLocalizations.of(context)!.categoryChildrensBooks,
      AppLocalizations.of(context)!.categoryYoungAdult,
      AppLocalizations.of(context)!.categoryClassicLit,
      AppLocalizations.of(context)!.categoryTranslated,
      AppLocalizations.of(context)!.categoryEssay,
      AppLocalizations.of(context)!.categoryGraphicNovel,
      AppLocalizations.of(context)!.categoryDystopianNovel,
      AppLocalizations.of(context)!.categoryAlternateHistory,
      AppLocalizations.of(context)!.categoryCyberpunk,
      AppLocalizations.of(context)!.categoryWomensLit,
      AppLocalizations.of(context)!.categorySelfImprovement,
    ];
  }

  // Veritabanı işlemleri için İngilizce kategori isimleri
  static List<String> get categoriesEN => [
        "Action",
        "Comedy",
        "Drama",
        "Thriller",
        "Horror",
        "Science Fiction",
        "Fantasy",
        "Animation",
        "Adventure",
        "War Movies",
        "Romantic Comedy",
        "Crime",
        "Psychological Thriller",
        "Historical",
        "Documentary",
        "Dystopian",
        "Superhero",
        "Spy",
        "Independent Films",
        "Anime",
        "Musical",
        "Western",
        "Noir",
        "Family Movies",
        "Supernatural",
      ];

  static List<String> get bookCategoriesEN => [
        "Novel",
        "Story",
        "Poetry",
        "Theatre",
        "Science Fiction",
        "Fantasy",
        "Dystopian",
        "Horror",
        "Detective",
        "Biography",
        "Autobiography",
        "History",
        "Travel Writing",
        "Diary",
        "Philosophy",
        "Psychology",
        "Sociology",
        "Science and Technology",
        "Political Science",
        "Romance Novels",
        "Psychological Novel",
        "Family Novels",
        "Children's Books",
        "Young Adult",
        "Classic Literature",
        "Translated Works",
        "Essay",
        "Graphic Novel",
        "Dystopian Novel",
        "Alternate History",
        "Cyberpunk",
        "Women's Literature",
        "Self Improvement",
      ];
}
