class CategoryNames {
  static const List<String> categories = [
    'Action',
    'Adventure',
    'Animation',
    'Comedy',
    'Asian',
    'Korean',
    'Crime',
    'Documentary',
    'Drama',
    'Family',
    'Fantasy',
    'Horror',
    'Mystery',
    'Romance',
    'Science Fiction',
    'Thriller',
    'War',
    'Western',
    'Biography',
    'History',
    'Sport'
  ];

  static const List<String> categoriesTR = [
    'Aksiyon',
    'Macera',
    'Animasyon',
    'Komedi',
    'Asya',
    'Kore',
    'Suç',
    'Belgesel',
    'Drama',
    'Aile',
    'Fantastik',
    'Korku',
    'Gizem',
    'Romantik',
    'Bilim Kurgu',
    'Gerilim',
    'Savaş',
    'Vahşi Batı',
    'Biyografi',
    'Tarih',
    'Spor'
  ];

  static const List<String> bookCategories = [
    'Fiction',
    'Self Improvement',
    'Mystery',
    'Romance',
    'Science Fiction',
    'Fantasy',
    'Horror',
    'Thriller',
    'Historical Fiction',
    'Literary Fiction',
    'Biography',
    'Business',
    'Poetry',
    'Crime',
    'Adventure',
    'Classics',
    'History',
    'Science',
    'Philosophy',
  ];

  static const List<String> bookCategoriesTR = [
    'Kurgu',
    'Kişisel Gelişim',
    'Gizem',
    'Romantik',
    'Bilim Kurgu',
    'Fantastik',
    'Korku',
    'Gerilim',
    'Tarihi Kurgu',
    'Edebi Kurgu',
    'Biyografi',
    'İş Dünyası',
    'Şiir',
    'Suç',
    'Macera',
    'Klasikler',
    'Tarih',
    'Bilim',
    'Felsefe',
  ];
}
